site_name: RDB Package Info documentation

theme:
  name: material
  # custom_dir: mkdocs-material/material

  # 404 page
  static_templates:
    - 404.html

  # Necessary for search to work properly
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  icon:
    logo: logo

plugins:
  - search
  - mkdocstrings

nav:
  - "My page": index.md

handlers:
  python:
    setup_commands:
      - import sys
      - sys.path.append("rdb_package_info")
